# Generated by Django 5.1.3 on 2024-11-30 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleaning", "0003_alter_train_end_time_alter_train_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cleaning.approval",
            ),
        ),
    ]
