# Generated by Django 5.1.3 on 2024-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0006_alter_train_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=7),
        ),
    ]
